# Generated by Django 3.1.1 on 2020-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0004_auto_20201030_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
