# Generated by Django 3.1.1 on 2020-10-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0005_auto_20201030_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
